"""Generate deploy/sql/auth/004_permissions.sql from a single source of truth.

Sources:
- ``config/project.yaml`` roles  -> table allowlists + denied columns per role
- ``project_core.domain.access.permission_set`` -> canonical tool capabilities

This keeps the AUTH DB seed in lockstep with the runtime/dev-fallback config so
tables, denied columns, and tool capability keys are never edited in two places.

Usage:
    python scripts/gen_rbac_seed.py            # write 004_permissions.sql
    python scripts/gen_rbac_seed.py --check     # fail if the file is stale
    python scripts/gen_rbac_seed.py --stdout    # print, do not write
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "project-core" / "src"))

from project_core.config.loader import load_project_config  # noqa: E402
from project_core.domain.access.permission_set import ALL_TOOL_CAPABILITIES  # noqa: E402

OUT_PATH = ROOT / "deploy" / "sql" / "auth" / "004_permissions.sql"

ROLE_DESCRIPTIONS = {
    "admin": "Full access (all tables, tools, functions)",
    "hq_analyst": "HQ analyst: broad table set, all tools/functions",
    "store_manager": "Store manager: restricted tables + denied columns + store filter",
}


def _tool_description(cap: str) -> str:
    # cap = "tool:<server>:<action>"
    parts = cap.split(":")
    if len(parts) == 3:
        return f"{parts[1]} {parts[2]}"
    return cap


def _values_block(rows: list[tuple[str, ...]]) -> str:
    return ",\n".join("    (" + ", ".join(f"'{c}'" for c in r) + ")" for r in rows)


def render() -> str:
    cfg = load_project_config()
    roles = cfg.roles

    catalog: list[tuple[str, str, str]] = [
        ("data:table:*", "data", "Access to all logical tables"),
        ("data:column_deny:*", "data", "Wildcard column denial marker"),
        ("data:store_filter:required", "data", "Force per-store filtering"),
        ("tool:*", "tool", "Invoke any MCP tool"),
    ]
    catalog += [(cap, "tool", _tool_description(cap)) for cap in ALL_TOOL_CAPABILITIES]
    catalog.append(("function:*", "function", "Run any promoted sandbox recipe"))

    role_rows = [(rk, ROLE_DESCRIPTIONS.get(rk, rk)) for rk in ("admin", *roles.keys())]
    # Dedupe roles preserving order (admin may also appear in yaml, though it usually does not).
    seen: set[str] = set()
    role_rows = [(rk, d) for rk, d in role_rows if not (rk in seen or seen.add(rk))]

    managed = ["admin", *roles.keys()]
    managed = [rk for rk in dict.fromkeys(managed)]

    # role -> capability grants derived from yaml + fixed policy.
    grants: list[tuple[str, str]] = [
        ("admin", "data:table:*"),
        ("admin", "tool:*"),
        ("admin", "function:*"),
    ]
    per_role_data: list[str] = []
    for role_key, rc in roles.items():
        for cap in rc.tool_grants:
            grants.append((role_key, cap))
        for cap in rc.allowed_functions:
            grants.append((role_key, cap))
        if rc.store_filter_required:
            grants.append((role_key, "data:store_filter:required"))

        table_rows = [(role_key, f"data:table:{t}") for t in rc.allowed_tables]
        deny_rows = [(role_key, f"data:column_deny:{c}") for c in rc.denied_columns]
        block = f"-- {role_key} tables (from config/project.yaml)\nINSERT INTO role_permissions (role_key, permission_key) VALUES\n{_values_block(table_rows)};"
        if deny_rows:
            block += (
                f"\n\n-- {role_key} denied columns (from config/project.yaml)\n"
                f"INSERT INTO role_permissions (role_key, permission_key) VALUES\n{_values_block(deny_rows)};"
            )
        per_role_data.append(block)

    managed_sql = ", ".join(f"'{rk}'" for rk in managed)

    return f"""-- Capability-based RBAC: permission catalog + role/user grants.
-- GENERATED by scripts/gen_rbac_seed.py from config/project.yaml + permission_set.
-- Do not edit by hand; run `python scripts/gen_rbac_seed.py` to regenerate.
-- Idempotent: safe to re-run. Resolution = role_permissions UNION user_permissions(grant)
--            MINUS user_permissions(revoke). Wildcards use ':*' (e.g. tool:*).

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------
IF OBJECT_ID('permissions', 'U') IS NULL
    CREATE TABLE permissions (
        permission_key NVARCHAR(200) NOT NULL PRIMARY KEY,
        category       NVARCHAR(32)  NOT NULL,   -- data | tool | function
        description    NVARCHAR(400) NULL
    );

IF OBJECT_ID('roles', 'U') IS NULL
    CREATE TABLE roles (
        role_key    NVARCHAR(64)  NOT NULL PRIMARY KEY,
        description NVARCHAR(400) NULL
    );

IF OBJECT_ID('role_permissions', 'U') IS NULL
    CREATE TABLE role_permissions (
        role_key       NVARCHAR(64)  NOT NULL,
        permission_key NVARCHAR(200) NOT NULL,
        CONSTRAINT PK_role_permissions PRIMARY KEY (role_key, permission_key)
    );

IF OBJECT_ID('user_permissions', 'U') IS NULL
    CREATE TABLE user_permissions (
        user_id        UNIQUEIDENTIFIER NOT NULL,
        permission_key NVARCHAR(200)    NOT NULL,
        effect         NVARCHAR(8)      NOT NULL CONSTRAINT DF_user_permissions_effect DEFAULT 'grant', -- grant | revoke
        CONSTRAINT PK_user_permissions PRIMARY KEY (user_id, permission_key)
    );

-- ---------------------------------------------------------------------------
-- Seed: permission catalog (informational; resolution uses the grant tables)
-- ---------------------------------------------------------------------------
MERGE permissions AS tgt
USING (VALUES
{_values_block(catalog)}
) AS src (permission_key, category, description)
ON tgt.permission_key = src.permission_key
WHEN MATCHED THEN UPDATE SET category = src.category, description = src.description
WHEN NOT MATCHED THEN INSERT (permission_key, category, description)
    VALUES (src.permission_key, src.category, src.description);

-- ---------------------------------------------------------------------------
-- Seed: roles
-- ---------------------------------------------------------------------------
MERGE roles AS tgt
USING (VALUES
{_values_block(role_rows)}
) AS src (role_key, description)
ON tgt.role_key = src.role_key
WHEN MATCHED THEN UPDATE SET description = src.description
WHEN NOT MATCHED THEN INSERT (role_key, description) VALUES (src.role_key, src.description);

-- ---------------------------------------------------------------------------
-- Seed: role_permissions (reseed the managed roles)
-- ---------------------------------------------------------------------------
DELETE FROM role_permissions WHERE role_key IN ({managed_sql});

INSERT INTO role_permissions (role_key, permission_key) VALUES
{_values_block(grants)};

{chr(10).join(per_role_data)}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args()

    content = render()
    if args.stdout:
        print(content)
        return 0
    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if current.strip() != content.strip():
            print(f"STALE: {OUT_PATH} is out of sync. Run: python scripts/gen_rbac_seed.py", file=sys.stderr)
            return 1
        print(f"OK: {OUT_PATH} is up to date.")
        return 0
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
