CREATE TABLE users (
    user_id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    email NVARCHAR(255) NOT NULL UNIQUE,
    display_name NVARCHAR(255) NOT NULL,
    role NVARCHAR(64) NOT NULL DEFAULT 'store_manager',
    store_ids NVARCHAR(512) NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE oauth_accounts (
    oauth_id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(user_id),
    provider NVARCHAR(64) NOT NULL,
    provider_user_id NVARCHAR(255) NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE sessions_audit (
    session_id NVARCHAR(64) PRIMARY KEY,
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(user_id),
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    last_seen_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
