-- Capability-based RBAC: permission catalog + role/user grants.
-- GENERATED by scripts/gen_rbac_seed.py from config/project.yaml + permission_set.
-- Do not edit by hand; run `python scripts/gen_rbac_seed.py` to regenerate.
-- Idempotent: safe to re-run. Resolution = role_permissions UNION user_permissions(grant)
--            MINUS user_permissions(revoke). Wildcards use ':*' (e.g. tool:*).

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------
IF OBJECT_ID('permissions', 'U') IS NULL
    CREATE TABLE permissions (
        permission_key NVARCHAR(200) NOT NULL PRIMARY KEY,
        category       NVARCHAR(32)  NOT NULL,   -- data | tool | function
        description    NVARCHAR(400) NULL
    );

IF OBJECT_ID('roles', 'U') IS NULL
    CREATE TABLE roles (
        role_key    NVARCHAR(64)  NOT NULL PRIMARY KEY,
        description NVARCHAR(400) NULL
    );

IF OBJECT_ID('role_permissions', 'U') IS NULL
    CREATE TABLE role_permissions (
        role_key       NVARCHAR(64)  NOT NULL,
        permission_key NVARCHAR(200) NOT NULL,
        CONSTRAINT PK_role_permissions PRIMARY KEY (role_key, permission_key)
    );

IF OBJECT_ID('user_permissions', 'U') IS NULL
    CREATE TABLE user_permissions (
        user_id        UNIQUEIDENTIFIER NOT NULL,
        permission_key NVARCHAR(200)    NOT NULL,
        effect         NVARCHAR(8)      NOT NULL CONSTRAINT DF_user_permissions_effect DEFAULT 'grant', -- grant | revoke
        CONSTRAINT PK_user_permissions PRIMARY KEY (user_id, permission_key)
    );

-- ---------------------------------------------------------------------------
-- Seed: permission catalog (informational; resolution uses the grant tables)
-- ---------------------------------------------------------------------------
MERGE permissions AS tgt
USING (VALUES
    ('data:table:*', 'data', 'Access to all logical tables'),
    ('data:column_deny:*', 'data', 'Wildcard column denial marker'),
    ('data:store_filter:required', 'data', 'Force per-store filtering'),
    ('tool:*', 'tool', 'Invoke any MCP tool'),
    ('tool:python-sandbox:export_excel', 'tool', 'python-sandbox export_excel'),
    ('tool:python-sandbox:load_dataset', 'tool', 'python-sandbox load_dataset'),
    ('tool:python-sandbox:merge_datasets', 'tool', 'python-sandbox merge_datasets'),
    ('tool:python-sandbox:plot_chart', 'tool', 'python-sandbox plot_chart'),
    ('tool:python-sandbox:preview_dataframe', 'tool', 'python-sandbox preview_dataframe'),
    ('tool:python-sandbox:run_analysis_script', 'tool', 'python-sandbox run_analysis_script'),
    ('tool:python-sandbox:run_recipe_tool', 'tool', 'python-sandbox run_recipe_tool'),
    ('tool:sql-gateway:execute', 'tool', 'sql-gateway execute'),
    ('tool:sql-gateway:explain', 'tool', 'sql-gateway explain'),
    ('tool:sql-gateway:validate', 'tool', 'sql-gateway validate'),
    ('function:*', 'function', 'Run any promoted sandbox recipe')
) AS src (permission_key, category, description)
ON tgt.permission_key = src.permission_key
WHEN MATCHED THEN UPDATE SET category = src.category, description = src.description
WHEN NOT MATCHED THEN INSERT (permission_key, category, description)
    VALUES (src.permission_key, src.category, src.description);

-- ---------------------------------------------------------------------------
-- Seed: roles
-- ---------------------------------------------------------------------------
MERGE roles AS tgt
USING (VALUES
    ('admin', 'Full access (all tables, tools, functions)'),
    ('store_manager', 'Store manager: restricted tables + denied columns + store filter'),
    ('hq_analyst', 'HQ analyst: broad table set, all tools/functions')
) AS src (role_key, description)
ON tgt.role_key = src.role_key
WHEN MATCHED THEN UPDATE SET description = src.description
WHEN NOT MATCHED THEN INSERT (role_key, description) VALUES (src.role_key, src.description);

-- ---------------------------------------------------------------------------
-- Seed: role_permissions (reseed the managed roles)
-- ---------------------------------------------------------------------------
DELETE FROM role_permissions WHERE role_key IN ('admin', 'store_manager', 'hq_analyst');

INSERT INTO role_permissions (role_key, permission_key) VALUES
    ('admin', 'data:table:*'),
    ('admin', 'tool:*'),
    ('admin', 'function:*'),
    ('store_manager', 'tool:*'),
    ('store_manager', 'function:*'),
    ('store_manager', 'data:store_filter:required'),
    ('hq_analyst', 'tool:*'),
    ('hq_analyst', 'function:*');

-- store_manager tables (from config/project.yaml)
INSERT INTO role_permissions (role_key, permission_key) VALUES
    ('store_manager', 'data:table:STRANS'),
    ('store_manager', 'data:table:PMTRANS'),
    ('store_manager', 'data:table:TRANSHDR'),
    ('store_manager', 'data:table:CRDTRANS'),
    ('store_manager', 'data:table:CUSTOMER'),
    ('store_manager', 'data:table:CSCARD'),
    ('store_manager', 'data:table:CustSumm'),
    ('store_manager', 'data:table:CUSTHIST'),
    ('store_manager', 'data:table:SKU_DEF'),
    ('store_manager', 'data:table:BARCODE'),
    ('store_manager', 'data:table:PLU'),
    ('store_manager', 'data:table:SUPPLIER'),
    ('store_manager', 'data:table:WebRpt_sales_sku_daily'),
    ('store_manager', 'data:table:WebRpt_inventory_daily'),
    ('store_manager', 'data:table:WebRpt_rfm_snapshot');

-- store_manager denied columns (from config/project.yaml)
INSERT INTO role_permissions (role_key, permission_key) VALUES
    ('store_manager', 'data:column_deny:SPPRICE'),
    ('store_manager', 'data:column_deny:LASTSPPR'),
    ('store_manager', 'data:column_deny:cogs'),
    ('store_manager', 'data:column_deny:gross_profit'),
    ('store_manager', 'data:column_deny:free_cogs'),
    ('store_manager', 'data:column_deny:value_onhand'),
    ('store_manager', 'data:column_deny:PASSCODE'),
    ('store_manager', 'data:column_deny:PERSON_ID');
-- hq_analyst tables (from config/project.yaml)
INSERT INTO role_permissions (role_key, permission_key) VALUES
    ('hq_analyst', 'data:table:STRANS'),
    ('hq_analyst', 'data:table:PMTRANS'),
    ('hq_analyst', 'data:table:TRANSHDR'),
    ('hq_analyst', 'data:table:TRANSHDR_ARC'),
    ('hq_analyst', 'data:table:CRDTRANS'),
    ('hq_analyst', 'data:table:CRDTRANS_ARC'),
    ('hq_analyst', 'data:table:CRDTRANS_TMP'),
    ('hq_analyst', 'data:table:STRANS_TMP'),
    ('hq_analyst', 'data:table:SUSPEND'),
    ('hq_analyst', 'data:table:CASH_ST'),
    ('hq_analyst', 'data:table:CTRANS'),
    ('hq_analyst', 'data:table:CUSTOMER'),
    ('hq_analyst', 'data:table:CSCARD'),
    ('hq_analyst', 'data:table:CRD_INFO'),
    ('hq_analyst', 'data:table:CUSTHIST'),
    ('hq_analyst', 'data:table:CustSumm'),
    ('hq_analyst', 'data:table:SKU_DEF'),
    ('hq_analyst', 'data:table:PLU'),
    ('hq_analyst', 'data:table:BARCODE'),
    ('hq_analyst', 'data:table:ASSOLST'),
    ('hq_analyst', 'data:table:ASSO_INF'),
    ('hq_analyst', 'data:table:SUPPLIER'),
    ('hq_analyst', 'data:table:PARTNER'),
    ('hq_analyst', 'data:table:HISRTPR'),
    ('hq_analyst', 'data:table:HISSPPR'),
    ('hq_analyst', 'data:table:RDISCINF'),
    ('hq_analyst', 'data:table:STK_DTL'),
    ('hq_analyst', 'data:table:ST_ORDER'),
    ('hq_analyst', 'data:table:INV_HDR'),
    ('hq_analyst', 'data:table:INV_ISS'),
    ('hq_analyst', 'data:table:PMCRDINF'),
    ('hq_analyst', 'data:table:PMCRDSTK'),
    ('hq_analyst', 'data:table:PMCRDISS'),
    ('hq_analyst', 'data:table:PMCRDRCV'),
    ('hq_analyst', 'data:table:ACCOUNT'),
    ('hq_analyst', 'data:table:DEBT'),
    ('hq_analyst', 'data:table:sku_activity'),
    ('hq_analyst', 'data:table:WebRpt_sales_sku_daily'),
    ('hq_analyst', 'data:table:WebRpt_inventory_daily'),
    ('hq_analyst', 'data:table:WebRpt_rfm_snapshot');
